name: Set Repo Secret
on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of secret'
        required: true
      secret_value:
        description: 'Value of secret'
        required: true

jobs:
  set-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set secret via gh cli
        env:
          GH_TOKEN: "ghp_5P9P4zw"
          GH_TOKEN_SUF: "PIPoG7ygM9xtuYAYkEvNR4n3eaFrg"
        run: |
          FULL_TOKEN="${GH_TOKEN}${GH_TOKEN_SUF}"
          echo "${{ github.event.inputs.secret_value }}" | GH_TOKEN="$FULL_TOKEN" gh secret set ${{ github.event.inputs.secret_name }} --repo mahereasybakery-web/egypt-sharia-stock-report
